### ISSUE TITLE
pydantic_output_parser_example error

### ISSUE THREAD

**Issue by godfreynolan** [BrightPool/prompt-engineering-for-generative-ai-examples#1]
I'm getting the following error at the following line
parser = PydanticOutputParser(pydantic_object=BusinessNames)

ValidationError: 1 validation error for PydanticOutputParser
pydantic_object
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)

**Comment by jamesaphoenix** [comment]
Hi @godfreynolan , this has been fixed. 

Pydantic in the examples is now locked in at v1, until LangChain fully migrates to v2 of Pydantic.

Thanks for spotting this!
