### ISSUE TITLE
chapter_4/document_loading.ipynb

### ISSUE THREAD

**Issue by godfreynolan** [BrightPool/prompt-engineering-for-generative-ai-examples#2]
Getting 404 error when I try to download  "NutriFusion Foods Marketing Plan 2022.docx" and "NutriFusion Foods Marketing Plan 2023.docx"

Fails on line 15    
pages = loader.load()

![image](https://github.com/BrightPool/prompt-engineering-for-generative-ai-examples/assets/658383/10a1ada0-82be-4eae-b2d6-da6a2f8573e7)

**Comment by jamesaphoenix** [comment]
Hi @godfreynolan, I've just made the Google Cloud Storage bucket public access, could you please try again?

**Comment by godfreynolan** [comment]
Still getting a 404 error.

![image](https://github.com/BrightPool/prompt-engineering-for-generative-ai-examples/assets/658383/f20392fa-4ca0-40a2-a5d3-a14cc6a9914c)

**Comment by jamesaphoenix** [comment]
Thanks for checking @godfreynolan, I'll likely remove this example as it looks like a `service-account.json` file is required.

**Comment by jamesaphoenix** [comment]
Hi @godfreynolan, I've updated this example to use `from langchain_community.document_loaders import Docx2txtLoader` instead with a public bucket URL.

Remember to install `docx2txt`

Thanks for finding the bug in this code, this has now been fixed :)
