### ISSUE TITLE
chapter5/self_query_retriever.ipynb

### ISSUE THREAD

**Issue by godfreynolan** [BrightPool/prompt-engineering-for-generative-ai-examples#3]
Towards the end of the notebook, the retriever fails on the following

![image](https://github.com/BrightPool/prompt-engineering-for-generative-ai-examples/assets/658383/06f19c99-3b0d-4e1d-9b72-8e9cfb1d88aa)

**Comment by jamesaphoenix** [comment]
I'll investigate this tomorrow, thanks again @godfreynolan

**Comment by jamesaphoenix** [comment]
It looks like there is a bug within LangChain's self-query retriever. I've tried implementing it and have the same problem whilst using LangChain Expression Language (LCEL).

I've removed any complicated self-queries as these were the ones which lead to incorrect lark expressions.
